/**
 * One-time setup: creates .env.local and DEPLOY-ENV.txt with all values
 * needed for local dev and Vercel. Run:  npm run setup
 */
import crypto from "crypto";
import fs from "fs";
import path from "path";
import bcrypt from "bcryptjs";

const root = path.resolve(import.meta.dirname, "..");
const adminPassword = "BristolVIP2026!";
const sessionSecret = crypto.randomBytes(48).toString("hex");
const passwordHash = bcrypt.hashSync(adminPassword, 12);

const envLocal = `# Auto-generated by npm run setup — do not commit
SESSION_SECRET=${sessionSecret}
ADMIN_PASSWORD=${adminPassword}
ADMIN_PASSWORD_HASH='${passwordHash}'
TICKET_LINK=https://www.eventbrite.co.uk/

# Optional: add Supabase keys later if you prefer Postgres over Vercel KV
# NEXT_PUBLIC_SUPABASE_URL=
# NEXT_PUBLIC_SUPABASE_ANON_KEY=
# SUPABASE_SERVICE_ROLE_KEY=

# Vercel KV vars are added automatically when you create a KV store in Vercel Storage

# Contact form — get a free key at https://resend.com
# RESEND_API_KEY=
`;

const deployGuide = `BRISTOL VIP — VERCEL ENVIRONMENT VARIABLES
==========================================
Copy each line into Vercel → Project → Settings → Environment Variables
Then redeploy.

SESSION_SECRET
${sessionSecret}

ADMIN_PASSWORD_HASH
${passwordHash}

ADMIN_PASSWORD (easier on Vercel — use this instead of the hash above)
BristolVIP2026!

TICKET_LINK
https://www.eventbrite.co.uk/

ADMIN LOGIN
URL:  /vip-manage-2026
Password: ${adminPassword}

ENABLE LIVE TICKET-LINK EDITING (pick one)
------------------------------------------
Option A (recommended on Vercel):
  1. Vercel project → Storage → Create Database → KV
  2. Connect to your project (env vars are added automatically)
  3. Redeploy — admin save will work instantly

Option B (Supabase):
  Add NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY and run supabase/schema.sql

CONTACT FORM EMAIL
------------------
1. Sign up at https://resend.com
2. Create API key → add in Vercel as RESEND_API_KEY
3. Redeploy — form submissions go to bristolvip1@gmail.com
`;

fs.writeFileSync(path.join(root, ".env.local"), envLocal);
fs.writeFileSync(path.join(root, "DEPLOY-ENV.txt"), deployGuide);

console.log("Created .env.local and DEPLOY-ENV.txt");
console.log(`Admin password: ${adminPassword}`);
console.log("Open DEPLOY-ENV.txt for Vercel copy-paste values.");
